### ISSUE TITLE
Execution file prompt error message

### ISSUE THREAD

**Issue by zhixiang520** [sabpprook/ozip2zip#12]
Hello, what's the reason why I run the information prompted by this file:
Traceback (most recent call last):
  File "ozipdecrypt.py", line 7, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

**Comment by zhixiang520** [comment]
I run the file with the CMD command of Windows 7 system.

**Comment by sabpprook** [comment]
Please install pycryptodome.
`pip install pycryptodome`
