### ISSUE TITLE
Realme X2 Pro Can't find the key

### ISSUE THREAD

**Issue by pranavbhushan13** [sabpprook/ozip2zip#18]
Desktop\ozip2zip-master>ozip2zip.py  RMX1931EX_11_OTA_0070_all_pPnzkNE5pNia.ozip
Can't find the key

**Comment by sabpprook** [comment]
everything looks good for me

![](https://i.imgur.com/EypUzpe.png)
![](https://i.imgur.com/Sdy3kD9.png)
