### ISSUE TITLE
Oppo A73的密钥是多少？

### ISSUE THREAD

**Issue by Vxer-Lee** [sabpprook/ozip2zip#6]
如题，貌似不支持oppo a73，希望能有oppo a73的密钥

**Comment by Kerrbty** [comment]
0xA1, 0xCC, 0x75, 0x11, 0x5C, 0xAE, 0xCB, 0x89, 0x0E, 0x4A, 0x56, 0x3C, 0xA1, 0xAC, 0x67, 0xC8

0x12, 0xCA, 0xC1, 0x12, 0x11, 0xAA, 0xC3, 0xAE, 0xA2, 0x65, 0x86, 0x90, 0x12, 0x2C, 0x1E, 0x81
总有一个适合你

**Comment by sabpprook** [comment]
done
