### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by bkerler** [sabpprook/ozip2zip#8]
You should have read the license before copying my code.

It would have been nice to have a reference to the original author or at least point to the repository if you just copy and paste, thanks :P

**Comment by sabpprook** [comment]
This project is not refer to your code.

Basically, it's from "oppo ozip2zip tool" made by @cofface
https://forum.xda-developers.com/android/software/cofface-oppo-ozip2zip-tool-t3653052

Anyway, thank for your notification :)
